name = "maollar-web"
pages_build_output_dir = "buyer/dist"

[env.buyer.vars]
CF_MODULE = "buyer"

[env.manager.vars]  
CF_MODULE = "manager"

[env.seller.vars]
CF_MODULE = "seller"

[env.im.vars]
CF_MODULE = "im"
